project:
  type: book
  preview: 
    port: 3434
    browser: true

book:
  title: Data Management Plan
  subtitle: "Washington Soil Health Initiative: State of the Soils Assessment"
  date: last-modified
  author: [Jadey Ryan, Leslie Michel, Dani Gelardi]
  sidebar: 
    search: true
    logo: images/washi_logo.jpg
  favicon: images/washi_circle.png
  downloads: [docx]
  repo-url: https://github.com/WA-Department-of-Agriculture/washi-dmp
  repo-actions: [issue]
  
  chapters:
    - index.qmd
    - formats.qmd
    - organization.qmd
    - documentation.qmd
    - flow.qmd
    - quality.qmd
    - preservation_version.qmd
    - share.qmd
    - code_guide.qmd
    - references.qmd

bibliography: references.bib
number-depth: 2
fig-align: left

format:
  html:
    mainfont: Poppins
    theme: 
      - flatly
      - style.scss
    toc-depth: 3
    link-external-newwindow: true
  docx:
    reference-doc: word_template.docx
    toc-depth: 2
