project:
  type: book
  preview: 
    port: 3434
    browser: true

execute: 
  freeze: auto
  
# lightbox extension
# https://github.com/quarto-ext/lightbox
filters:
  - lightbox
lightbox:
  desc-position: right  # position of description
  match: auto # give all images lightbox treatment
  effect: zoom # how lightbox opens/closes
  loop: false # doesn't loop to first image in gallery

book:
  title: Data Management Plan
  subtitle: "Washington Soil Health Initiative: State of the Soils Assessment"
  author: [Jadey Ryan, Dani Gelardi]
  date: last-modified
  favicon: images/washi-circle.png
  repo-url: https://github.com/WA-Department-of-Agriculture/washi-dmp
  repo-actions: [source, edit]
  
  sidebar: 
    search: true
    logo: images/washi-logo.jpg
    tools:
      - icon: download
        menu:
          - text: PDF
            url: sos-data-management-plan.pdf
          - text: MS Word
            url: sos-data-management-plan.docx
            
  chapters:
    - index.qmd
    - data-management.qmd
    - formats-standards.qmd
    - naming.qmd
    - organization.qmd
    - storage.qmd
    - documentation.qmd
    - flow.qmd
    - share.qmd
    - code-guide.qmd
    - references.qmd

bibliography: references.bib
number-depth: 2
fig-align: left

format:
  html:
    mainfont: Poppins
    theme: 
      - flatly
      - style.scss
    toc-depth: 3
    link-external-newwindow: true
  docx:
    reference-doc: word-template.docx
    toc-depth: 2
