project:
  type: book
  preview: 
    port: 3434
    browser: true

execute: 
  freeze: auto

book:
  title: Data Management Plan
  subtitle: "Washington Soil Health Initiative: State of the Soils Assessment"
  date: last-modified
  author: [Jadey Ryan, Dani Gelardi]
  sidebar: 
    search: true
    logo: images/washi-logo.jpg
  favicon: images/washi-circle.png
  repo-url: https://github.com/WA-Department-of-Agriculture/washi-dmp
  repo-actions: [source, edit]
  
  chapters:
    - index.qmd
    - data-management.qmd
    - formats-standards.qmd
    - naming.qmd
    - organization.qmd
    - storage.qmd
    - documentation.qmd
    - flow.qmd
    - share.qmd
    - code-guide.qmd
    - references.qmd

bibliography: references.bib
number-depth: 2
fig-align: left

format:
  html:
    mainfont: Poppins
    theme: 
      - flatly
      - style.scss
    toc-depth: 3
    link-external-newwindow: true
  docx:
    reference-doc: word-template.docx
    toc-depth: 2
