# Data infrastructure

## Expected data {#sec-expected-data}

The list below is not exhaustive and will continue to grow as additional useful data sources are discovered.

| **Type**                   | **Source**                                                                                                                                                    | **Formats**                                    |
|----------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|
| **Lab results**            | Provided by the lab analyzing the soil sample, principal investigator of a study, or grower                                                                   | csv, xlsx, pdf, RData                          |
| **Management surveys**     | Collected through interviews with grower                                                                                                                      | csv, xlsx, RData, paper form (to be digitized) |
| **Field forms**            | Completed in the field during/immediately after sampling                                                                                                      | pdf, paper form (to be digitized), csv, xlsx   |
| **Sample locations**       | Identified prior to sampling and may be edited during sampling using ArcGIS Online, Collector, Field Maps or Google Maps                                      | ArcGIS feature layer, shp, kmz, csv, xlsx      |
| **Chain of custody forms** | Completed prior to shipping or dropping off samples                                                                                                           | pdf, paper form (to be digitized)              |
| **Climate data**           | [OSU PRISM](https://prism.oregonstate.edu/), [NOAA](https://www.ncdc.noaa.gov/cdo-web/datasets), [Esri Living Atlas](https://livingatlas.arcgis.com/en/home/) | csv, shp, netCDF, tiff, gdb                    |
| **Soil data**              | [NRCS Web Soil Survey](https://websoilsurvey.sc.egov.usda.gov/App/HomePage.htm), [NRCS WA gSSURGO](K:\NRAS\Arc_Data\Soil_Health\NRCS_StatewideSoils)          | gdb, accdb                                     |
| **Strata classification**  | Provided by Soil Health Institute in 2021 as a [lyr file](K:\NRAS\Arc_Data\Soil_Health\SoilHealthInstitute_Strata)                                            | lyr                                            |
| **Images**                 | Logos, icons, photos taken in the field                                                                                                                       | jpeg, png, gif, tiff, svg                      |
| **Videos**                 | Recordings of meetings, training videos                                                                                                                       | mp4                                            |
| **Documents**              | Reports, manuscripts, SOP, QAPP, factsheets, brochures                                                                                                        | docx, txt, html, pdf                           |
| **Presentations**          | Powerpoints, slide decks                                                                                                                                      | pptx, html, pdf                                |
| **Code**                   | Scripts for wrangling, processing, analyzing data; markdown for producing documents and presentations; style sheets for html outputs                          | R, py, ipynb, js, yml, rmd, qmd, css, scss     |

## Data standards {#sec-data-standards}

-   **Date and time** data will be expressed according to the [ISO 8601 standard](https://www.iso.org/iso-8601-date-and-time-format.html): YYYY-MM-DD**T**HH:MM:SS**Z**.
    -   Note the **T** is included as a separator between date and time. The **Z** indicates the date-time is using the Universal Time Coordinated (UTC) with no offset.
    -   Pacific Standard Time (PST) has a UTC-8:00 offset and Pacific Daylight Time (PDT) has a UTC-7:00 offset and would be expressed as YYYY-MM-DD**T**HH:MM:SS-8:00. The **Z** has been replaced with the offset.
-   **Geospatial** data will be accompanied by metadata that abides by the [ISO 19115 standard](https://www.iso.org/standard/53798.html) by following Esri's [documentation](https://pro.arcgis.com/en/pro-app/latest/help/metadata/create-iso-19115-and-iso-19139-metadata.htm) when working in ArcGIS Pro. Metadata contains information about the identification, the extent, the quality, the spatial and temporal schema, spatial reference, and distribution of digital geographic data.

## Storage {#sec-storage}

-   WSDA agency files shared drive

-   WSDA GIS shared drive

-   ArcGIS Online

-   WISKI

-   GitHub

-   Microsoft Teams

    -   WSDA and WSU Teams channels

-   Local workstations

## Naming Conventions and File Organization {#sec-naming-conventions-and-file-organization}

Dates in ISO 19115

camelCase

Records Management link
